on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright
        run: pnpx playwright install --with-deps
      - name: Run your tests
        run: pnpm run test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
