on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install yarn
        run: npm i -g yarn
      - name: Link libs
        run: cd libs/types && yarn link
      - name: Install dependencies
        run: yarn
      - name: Install globaly Playwright
        run: yarn global add playwright
      - name: Install Playwright
        run: playwright install --with-deps
      - name: Run your tests
        run: yarn test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
